name: Go

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Test on Go ${{ matrix.go-version }} and Ubuntu
    runs-on: self-hosted
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
    steps:
      - name: Set up Go ${{ matrix.go-version }} on Ubuntu
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build on Ubuntu
        env:
          GO111MODULE: on
        run: go test -v -race ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: go vet
        run: go vet ./...

      - name: go fmt
        run: diff <(gofmt -d .) <(printf "")

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          $(go env GOPATH)/bin/golangci-lint run --timeout=5m --config ./.golangci.yml
