name: Publish packages

on:
  push:
    branches:
      - 'master'

jobs:
  publish:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.x
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --skip=publish --snapshot
      -
        name: Upload binaries and packages to nexus
        shell: bash
        if: success()
        run: |
          set -e 

          # Create the summary section too
          echo "## Snapshot Build and publish Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Build commit**: ${{github.sha}}  " >> $GITHUB_STEP_SUMMARY

          version="snapshot_$(date +'%Y-%m-%d_%H-%M-%S')"
          base_directory="warp-ddn/$version"
          pkgs_directory="$base_directory/pkgs"
          bin_directory="$base_directory/bin"

          echo "### Packages downloads" >> $GITHUB_STEP_SUMMARY
          echo "| OS and Architecture | Download Link |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          for file in $(find dist -name *.deb); do
            filename=$(basename $file)
            curl -u "${{ secrets.NEXUS_RW_LOGIN }}:${{ secrets.NEXUS_RW_PASSWORD }}" \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: multipart/form-data" \
                "https://nexus.redlab.datadirectnet.com/service/rest/v1/components?repository=cicd" \
                -F "raw.directory=$pkgs_directory" \
                -F "raw.asset1=@$file;type=application/gzip" \
                -F "raw.asset1.filename=$filename"
            # Create summary row
            # os_arch eg: Linux_arm64
            os_arch=$(echo $file | sed -r "s/.*ddn_(.*).deb/\1/")
            url="https://nexus.redlab.datadirectnet.com/repository/cicd/$pkgs_directory/$filename" 
            echo "| $os_arch | [Download]($url)" >> $GITHUB_STEP_SUMMARY
          done
          echo "" >> $GITHUB_STEP_SUMMARY


          echo "### Binaries downloads" >> $GITHUB_STEP_SUMMARY
          echo "| OS and Architecture | Download Link |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY

          # Publish only for macos windows and linux
          files=$(find . -type f \( -name "warp-ddn" -o -name "warp-ddn.exe" \) \( -path "*darwin*" -o -path "*windows*" -o -path "*linux*" \))
          for file in $files; do
            # os_arch eg. for ./dist/warp-ddn_darwin_amd64_v1/warp-ddn gives darwin_amd64
            os_arch=$(echo $file | sed -r "s/.*warp-ddn_([a-z]+)_([a-z0-9]+).*/\1_\2/")
            final_dir="$bin_directory/$os_arch"
            filename=$(basename $file)
            curl -u "${{ secrets.NEXUS_RW_LOGIN }}:${{ secrets.NEXUS_RW_PASSWORD }}" \
                -X POST \
                -H "Accept: application/json" \
                -H "Content-Type: multipart/form-data" \
                "https://nexus.redlab.datadirectnet.com/service/rest/v1/components?repository=cicd" \
                -F "raw.directory=$final_dir" \
                -F "raw.asset1=@$file;type=application/gzip" \
                -F "raw.asset1.filename=$filename"
            # Create summary row
            url="https://nexus.redlab.datadirectnet.com/repository/cicd/$final_dir/$filename" 
            echo "| $os_arch | [Download]($url)" >> $GITHUB_STEP_SUMMARY
          done
          echo "" >> $GITHUB_STEP_SUMMARY
